### ISSUE TITLE
Exception on install from webui

### ISSUE THREAD

**Issue by a-l-e-x-d-s-9** [Extraltodeus/depthmap2mask#1]
Getting the following exception:
``` log
Error completing request
Arguments: ('', 'https://github.com/Extraltodeus/depthmap2mask') {}
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/modules/ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "/home/user/stable-diffusion-webui/modules/ui_extensions.py", line 111, in install_extension_from_url
    check_access()
  File "/home/user/stable-diffusion-webui/modules/ui_extensions.py", line 20, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabed because of commandline flags"
AssertionError: extension access disabed because of commandline flags
```
I'm using the command lines arguments: --api --listen --xformers --force-enable-xformers

Any idea what's wrong?

**Comment by Extraltodeus** [comment]
You need the launch argument --enable-insecure-extension-access in order to be able to isntall extensions from the webui if you use a gradio session.
