### ISSUE TITLE
Error if midas_v21 or dpt_large are used

### ISSUE THREAD

**Issue by celiaafisher** [Extraltodeus/depthmap2mask#12]
If I use midas_v21 or dpt_large on any image, I receive this error:

UnboundLocalError: local variable 'model' referenced before assignment

I have tried installing both manually and using the automatic install method.
midas_v21_small works fine.

**Comment by Extraltodeus** [comment]
> UnboundLocalError: local variable 'model' referenced before assignment

That error comes when the depth analysis script can not load. Which python version do you use by the way?

**Comment by korrasam** [comment]
> > UnboundLocalError: local variable 'model' referenced before assignment
> 
> That error comes when the depth analysis script can not load. Which python version do you use by the way?

i have the same issue , python ver. [Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]]
using automatic webui
runing on rocm 5.2  
gpu :rx 6800m

**Comment by Wukong1-137** [comment]
Im having the same issue. Running with Python 3.11.0, Auto1111 webui, and an Nvidia 3060

**Comment by celiaafisher** [comment]
I have Python 3.10.7, Auto1111 webui, and a Nvidia 2070

**Comment by AugmentedRealityCat** [comment]
I tried removing the models from the `./models/midas/` folder to see if it would generate the same error, but the depthmap2mask extension actually fixes this problem all by itself by downloading any missing model the moment you use them. 

Just for your information, since this is not a bug, here is the message I got when I removed `midas_v21_small` :
```
./models/midas/midas_v21_small-70d6b9c8.pt
Downloading midas model weights to ./models/midas/midas_v21_small-70d6b9c8.pt
Loading weights:  ./models/midas/midas_v21_small-70d6b9c8.pt
```
I guess you don't get anything like this in your log window when trying to use `midas_v21` or `dpt_large`  ?
Have you tried removing any of the two models that don't work? Does it try to download them if you try to use them after?

**Comment by Wukong1-137** [comment]
I removed Midas and redownloaded it. it gave me the same error I got last time, where it says the file might be corrupted, that would be the second time in a row, however, so I'm guessing it's not that. I will copy the text wall that I got in case that helps.

I also removed the DPT Large and will try again with that one, but I have to get some sleep. I will update in the morning.

Here comes the text wall of errors and other stuff that doesnt mean much to me but might make sense to people who know...

Downloading midas model weights to ./models/midas/midas_v21-f6b98070.pt
Loading weights:  ./models/midas/midas_v21-f6b98070.pt
Using cache found in C:\Users\Wukong/.cache\torch\hub\facebookresearch_WSL-Images_main
Error completing request
Arguments: (0, 'cyberware style, a (((scorpions tail))) made of muscle and bone rising from the ground and reaching into the sky, highly detailed, low-angle shot, gloomy sky, god rays', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=512x768 at 0x220B70756C0>, None, None, None, 0, 50, 17, 4, 1, False, False, 8, 1, 15, 0.4, -1.0, -1.0, 0, 0, 0, False, 768, 512, 1, False, 32, 0, '', '', 11, '<div class="dynamic-prompting">\n    <h3><strong>Combinations</strong></h3>\n\n    Choose a number of terms from a list, in this case we choose two artists: \n    <code class="codeblock">{2$$artist1|artist2|artist3}</code><br/>\n\n    If $$ is not provided, then 1$$ is assumed.<br/><br/>\n\n    If the chosen number of terms is greater than the available terms, then some terms will be duplicated, otherwise chosen terms will be unique. This is useful in the case of wildcards, e.g.\n    <code class="codeblock">{2$$__artist__}</code> is equivalent to <code class="codeblock">{2$$__artist__|__artist__}</code><br/><br/>\n\n    A range can be provided:\n    <code class="codeblock">{1-3$$artist1|artist2|artist3}</code><br/>\n    In this case, a random number of artists between 1 and 3 is chosen.<br/><br/>\n\n    Wildcards can be used and the joiner can also be specified:\n    <code class="codeblock">{{1-$$and$$__adjective__}}</code><br/>\n\n    Here, a random number between 1 and 3 words from adjective.txt will be chosen and joined together with the word \'and\' instead of the default comma.\n\n    <br/><br/>\n\n    <h3><strong>Wildcards</strong></h3>\n    \n\n    <br/>\n    If the groups wont drop down click <strong onclick="check_collapsibles()" style="cursor: pointer">here</strong> to fix the issue.\n\n    <br/><br/>\n\n    <code class="codeblock">WILDCARD_DIR: D:\\Stable Diffusion Automatic1111\\stable-diffusion-webui\\extensions\\sd-dynamic-prompts\\wildcards</code><br/>\n    <small onload="check_collapsibles()">You can add more wildcards by creating a text file with one term per line and name is mywildcards.txt. Place it in D:\\Stable Diffusion Automatic1111\\stable-diffusion-webui\\extensions\\sd-dynamic-prompts\\wildcards. <code class="codeblock">__&#60;folder&#62;/mywildcards__</code> will then become available.</small>\n</div>\n\n', True, False, 1, False, False, False, 100, 0.7, False, False, False, False, False, False, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, 1, '', 0, '', True, False, False, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', '<p style="font-weight:bold;margin-bottom:0.75em">Deforum v0.5-webui-beta</p>', '<p>This script is deprecated. Please use the full Deforum extension instead.<br>\nUpdate instructions:</p>', '<p>github.com/deforum-art/deforum-for-automatic1111-webui/blob/automatic1111-webui/README.md</p>', '<p>discord.gg/deforum</p>', True, 0, True, 384, 384, False, 1, True, True, False, 0, 0, 384, 384, False, False, True, True, True, 1, '{inspiration}', None) {}
Traceback (most recent call last):
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\extensions/depthmap2mask/scripts/depthmap_for_depth2img.py", line 74, in calculate_depth_maps
    model = MidasNet(model_path, non_negative=True)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\repositories\midas\midas\midas_net.py", line 30, in __init__
    self.pretrained, self.scratch = _make_encoder(backbone="resnext101_wsl", features=features, use_pretrained=use_pretrained)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 37, in _make_encoder
    pretrained = _make_pretrained_resnext101_wsl(use_pretrained)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 115, in _make_pretrained_resnext101_wsl
    resnet = torch.hub.load("facebookresearch/WSL-Images", "resnext101_32x8d_wsl")
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 540, in load    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 569, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\Wukong/.cache\torch\hub\facebookresearch_WSL-Images_main\hubconf.py", line 39, in resnext101_32x8d_wsl
    return _resnext('resnext101_32x8d', Bottleneck, [3, 4, 23, 3], True, progress, **kwargs)
  File "C:\Users\Wukong/.cache\torch\hub\facebookresearch_WSL-Images_main\hubconf.py", line 24, in _resnext
    state_dict = load_state_dict_from_url(model_urls[arch], progress=progress)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\hub.py", line 731, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\modules\safe.py", line 102, in load
    return load_with_extra(filename, *args, **kwargs)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\modules\safe.py", line 147, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 938, in _legacy_load
    typed_storage._storage._set_from_file(
RuntimeError: unexpected EOF, expected 1356128 more bytes. The file might be corrupted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\modules\img2img.py", line 137, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\modules\scripts.py", line 317, in run
    processed = script.run(p, *script_args)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\extensions\depthmap2mask\scripts\depth2image_depthmask.py", line 81, in run
    d_m = sdmg.calculate_depth_maps(p.init_images[0],img_x,img_y,model_type,invert_depth)
  File "D:\Stable Diffusion Automatic1111\stable-diffusion-webui\extensions/depthmap2mask/scripts/depthmap_for_depth2img.py", line 169, in calculate_depth_maps
    del model
UnboundLocalError: local variable 'model' referenced before assignment

**Comment by Rogal80** [comment]
Same here with large model

UnboundLocalError: local variable 'model' referenced before assignment

**Comment by korrasam** [comment]
so for all of u out there still having the same issue , the solution for me was to simple just delete the model that was downloaded earlier and download the model manually from this link https://github.com/intel-isl/DPT/releases/download/1_0/dpt_large-midas-2f21e586.pt then place in models folder
