### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'extensions/depthmap2mask/scripts/depthmap_for_depth2img.py'

### ISSUE THREAD

**Issue by wilzamguerrero** [Extraltodeus/depthmap2mask#14]
Hi i hope you are fine i have a problem with the extension 

FileNotFoundError: [Errno 2] No such file or directory: 'extensions/depthmap2mask/scripts/depthmap_for_depth2img.py'

Connected
Error completing request
Arguments: (0, '', '', 'None', 'None', <PIL.Image.Image image mode=RGB size=512x512 at 0x7FD06CA987D0>, None, None, None, 0, 20, 0, 4, 1, False, False, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, False, 32, 0, '', '', 9, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image to twice the dimensions; use width and height sliders to set tile size</p>', 64, 0, 1, '', 0, '', True, False, False, False, 0, True, 384, 384, False, 2, True, True, False) {}
Traceback (most recent call last):

 File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'extensions/depthmap2mask/scripts/depthmap_for_depth2img.py'

**Comment by brennop** [comment]
Had the same error on a google colab. Had to change the line to have a absolute import instead of a relative one.

**Comment by wilzamguerrero** [comment]
You can tell me how do you change this, or what line you change

**Comment by djcedr** [comment]
Hi, I have the same problem - how/where do you 'change the line to have a absolute import instead of a relative one.' please? @brennop ?

**Comment by wilzamguerrero** [comment]
> Hi, I have the same problem - how/where do you 'change the line to have a absolute import instead of a relative one.' @brennop please? I tried to change the destination folder in the line I added to colab before the block that launches the webUI, but it didn't change anything...
> 
> ```
> !git clone https://github.com/Extraltodeus/depthmap2mask.git /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/depthmap2mask
> ```
> 
> instead of
> 
> ```
> !git clone https://github.com/Extraltodeus/depthmap2mask.git /content/stable-diffusion-webui/extensions/depthmap2mask
> ```

well you can watch my repo i try to do other implementation more simply about sd, with custom path and other things, https://github.com/wilzamguerrero/SDZ
![image](https://user-images.githubusercontent.com/110712636/205490366-1ddd3f20-7c2c-45c8-a93d-8ae3f6ca8a02.png)
