### ISSUE TITLE
Error loading script: depthmap_for_depth2img.py

### ISSUE THREAD

**Issue by trdahl** [Extraltodeus/depthmap2mask#52]
Im getting this error after installing this extension in Stable Diffusion, any1 know how to fix this?

Error loading script: depthmap_for_depth2img.py
Traceback (most recent call last):
  File "C:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\depthmap2mask\scripts\depthmap_for_depth2img.py", line 13, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "C:\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "C:\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\midas\midas\blocks.py", line 4, in <module>
    from .backbones.beit import (
  File "C:\A1111 Web UI Autoinstaller\stable-diffusion-webui\repositories\midas\midas\backbones\beit.py", line 9, in <module>
    from timm.models.beit import gen_relative_position_index
ModuleNotFoundError: No module named 'timm.models.beit'

**Comment by magestyx** [comment]
You should search before posting.
There's already been a lengthy discussion of this issue here: https://github.com/Extraltodeus/depthmap2mask/issues/35
